services:
    read_model.projector.account:
        class: AppBundle\Read\Projector\UserProjector
        arguments:
            - @read_model.repository.user
        tags:
            - { name: broadway.domain.event_listener }
