services:
    read_model.projector.user:
        class: AppBundle\Read\Projector\UserProjector
        arguments:
            - @read_model.repository.user
        tags:
            - { name: broadway.domain.event_listener }

    read_model.projector.employee:
        class: AppBundle\Read\Projector\EmployeeProjector
        arguments:
            - @read_model.repository.employee
        tags:
            - { name: broadway.domain.event_listener }

    read_model.projector.company:
        class: AppBundle\Read\Projector\CompanyProjector
        arguments:
            - @read_model.repository.company
        tags:
            - { name: broadway.domain.event_listener }
