services:
    read_model.projector.account:
        class: AppBundle\Read\Projector\LoginProjector
        arguments:
            - "@=service('doctrine').getManager()"
        tags:
            - { name: broadway.domain.event_listener }

    read_model.projector.company:
        class: AppBundle\Read\Projector\CompanyProjector
        arguments:
            - "@=service('doctrine').getManager()"
        tags:
            - { name: broadway.domain.event_listener }
