# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.mailer:
        class: AppBundle\Infra\Mailer\TwigMailer
        arguments:
            - @mailer
            - @twig
            -
                from_email: sender@domain.com
                from_name: Sender


    app.security.user_provider:
        class: AppBundle\Security\User\UserProvider
        arguments:
            - @read_model.repository.user

    app.event_player:
        class: AppBundle\Infra\EventPlayer\DBALEventPlayer
        arguments:
            - @broadway.event_store.dbal.connection
            - @broadway.serializer.payload
            - @broadway.serializer.metadata
            - %broadway.event_store.dbal.table%
            - %broadway.event_store.dbal.use_binary%

    app.cmd.readmodel_rebuild:
        class: AppBundle\Command\ReadModelReplyEventsCommand
        arguments:
            - @app.event_player
        tags:
            - { name: console.command }

    read_model.index_generator:
        class: AppBundle\Infra\ReadModel\ElasticSearchIndexGenerator
        arguments:
            -
                - @read_model.repository.user
                - @read_model.repository.employee
                - @read_model.repository.company
